version: "3.9"
services:
  backend:
    build: ./backend
    container_name: fitness_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: fitness_frontend
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: supabase
      POSTGRES_PASSWORD: supabase
      POSTGRES_DB: supabase
    ports:
      - "5432:5432"
